---
- name: Obtain Percona public key
  # apt_key: url=http://keys.gnupg.net/pks/lookup?op=get&search=0x1C4CBDCDCD2EFD2A
  apt_key: url=http://www.percona.com/downloads/RPM-GPG-KEY-percona
           state=present

- name: Add Percona repository
  apt_repository: repo='deb http://repo.percona.com/apt trusty main'
                  state=present

- name: Add Percona source repository
  apt_repository: repo='deb-src http://repo.percona.com/apt trusty main'
                  state=present

- name: Update apt cache
  apt: update_cache=yes

